{
  "openapi": "3.1.0",
  "info": {
    "version": "1.0.0",
    "title": "Contacts App",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "description": "API documentation for Contacts App"
  },
  "servers": [
    {
      "url": "https://nodejs-hw-mongodb-3-06yw.onrender.com/api/v1"
    }
  ],
  "tags": [
    {
      "name": "Contacts",
      "description": "Operations about contacts"
    },
    {
      "name": "Auth",
      "description": "Operations about user authentication"
    }
  ],
  "paths": {
    "/auth/register": {
      "post": {
        "tags": ["Auth"],
        "operationId": "registerUser",
        "summary": "Register a new user",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserRegistration"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User registered successfully",
            "content": {
              "application/json": {
                "example": {
                  "status": 201,
                  "message": "Successfully registered a user!",
                  "data": {
                    "name": "Oleksii",
                    "email": "oleksii@example.com",
                    "_id": "670bb07661d02f82f21ab999",
                    "createdAt": "024-10-13T11:35:18.404Z",
                    "updatedAt": "024-10-13T11:35:18.404Z"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "status": 400,
                  "message": "BadRequestError",
                  "data": {
                    "message": "Bad Request",
                    "errors": [
                      {
                        "message": "\"password\" is required",
                        "path": ["password"],
                        "type": "any.required",
                        "context": {
                          "label": "password",
                          "key": "password"
                        }
                      }
                    ]
                  }
                }
              }
            }
          },
          "409": {
            "description": "Email in use",
            "content": {
              "application/json": {
                "example": {
                  "status": 409,
                  "message": "ConflictError",
                  "data": {
                    "message": "Email in use"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "tags": ["Auth"],
        "operationId": "loginUser",
        "summary": "Login user",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserLogin"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User logged in successfully",
            "content": {
              "application/json": {
                "example": {
                  "status": 200,
                  "message": "Successfully logged in an user!",
                  "data": {
                    "accessToken": "sD5E+jdfyhoaySJe2ikJA0iuhN0eO8OnTGSM7RHh"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Login failed",
            "content": {
              "application/json": {
                "example": {
                  "status": 400,
                  "message": "BadRequestError",
                  "data": {
                    "message": "Bad Request",
                    "errors": [
                      {
                        "message": "\"password\" length must be at least 8 characters long",
                        "path": ["password"],
                        "type": "string.min",
                        "context": {
                          "limit": 8,
                          "value": "145678",
                          "label": "password",
                          "key": "password"
                        }
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Missing header with authorization token.",
            "content": {
              "application/json": {
                "example": {
                  "status": 401,
                  "message": "UnauthorizedError",
                  "data": {
                    "message": "Session not found"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server Error"
          }
        }
      }
    },
    "/auth/send-reset-email": {
      "post": {
        "tags": ["Auth"],
        "operationId": "sendResetEmail",
        "summary": "Send password reset email",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["email"],
                "properties": {
                  "email": {
                    "type": "string",
                    "example": "oleksii@example.com"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Reset email sent successfully",
            "content": {
              "application/json": {
                "example": {
                  "message": "Reset password email has been successfully sent.",
                  "status": 200,
                  "data": {}
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "status": 400,
                  "message": "BadRequestError",
                  "data": {
                    "message": "Bad Request",
                    "errors": [
                      {
                        "message": "\"email\" must be a valid email",
                        "path": ["email"],
                        "type": "string.email",
                        "context": {
                          "value": "123@g",
                          "invalids": ["123@g"],
                          "label": "email",
                          "key": "email"
                        }
                      }
                    ]
                  }
                }
              }
            }
          },
          "404": {
            "description": "User not found",
            "content": {
              "application/json": {
                "example": {
                  "status": 404,
                  "message": "NotFoundError",
                  "data": {
                    "message": "User not found!"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/auth/reset-pwd": {
      "post": {
        "tags": ["Auth"],
        "operationId": "resetPassword",
        "summary": "Reset user password",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["token", "password"],
                "properties": {
                  "token": {
                    "type": "string",
                    "description": "JWT token from reset email"
                  },
                  "password": {
                    "type": "string",
                    "example": "newpasswordpassword"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Password reset successfully"
          },
          "400": {
            "description": "Password reseting failed",
            "content": {
              "application/json": {
                "example": {
                  "status": 400,
                  "message": "BadRequestError",
                  "data": {
                    "message": "Bad Request",
                    "errors": [
                      {
                        "message": "\"password\" is required",
                        "path": ["password"],
                        "type": "any.required",
                        "context": {
                          "label": "password",
                          "key": "password"
                        }
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Missing header with authorization token.",
            "content": {
              "application/json": {
                "example": {
                  "status": 401,
                  "message": "UnauthorizedError",
                  "data": {
                    "message": "Session not found"
                  }
                }
              }
            }
          },
          "404": {
            "description": "User not found",
            "content": {
              "application/json": {
                "example": {
                  "status": 404,
                  "message": "NotFoundError",
                  "data": {
                    "message": "User not found!"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server Error"
          }
        }
      }
    },
    "/auth/logout": {
      "post": {
        "tags": ["Auth"],
        "operationId": "logoutUser",
        "summary": "Logout user",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "204": {
            "description": "User logged out successfully"
          },
          "401": {
            "description": "Missing header with authorization token.",
            "content": {
              "application/json": {
                "example": {
                  "status": 401,
                  "message": "UnauthorizedError",
                  "data": {
                    "message": "Session not found"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server Error"
          }
        }
      }
    },
    "/contacts": {
      "get": {
        "tags": ["Contacts"],
        "operationId": "getContacts",
        "summary": "Get all contacts",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "description": "The page number for pagination",
            "required": false,
            "schema": {
              "type": "integer",
              "example": 1
            }
          },
          {
            "name": "perPage",
            "in": "query",
            "description": "Number of items per page",
            "required": false,
            "schema": {
              "type": "integer",
              "example": 10
            }
          },
          {
            "name": "sortBy",
            "in": "query",
            "description": "Field to sort by",
            "required": false,
            "schema": {
              "type": "string",
              "example": "name"
            }
          },
          {
            "name": "sortOrder",
            "in": "query",
            "description": "Sort order (asc or desc)",
            "required": false,
            "schema": {
              "type": "string",
              "enum": ["asc", "desc"],
              "example": "asc"
            }
          },
          {
            "name": "name",
            "in": "query",
            "description": "Filter contacts by name",
            "required": false,
            "schema": {
              "type": "string",
              "example": "Oleksii"
            }
          },
          {
            "name": "isFavourite",
            "in": "query",
            "description": "Filter contacts by favourite status",
            "required": false,
            "schema": {
              "type": "boolean",
              "example": true
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Contacts retrieved successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ContactsList"
                }
              }
            }
          },
          "401": {
            "description": "Missing header with authorization token.",
            "content": {
              "application/json": {
                "example": {
                  "status": 401,
                  "message": "UnauthorizedError",
                  "data": {
                    "message": "Session not found"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server error."
          }
        }
      },
      "post": {
        "tags": ["Contacts"],
        "operationId": "createContact",
        "summary": "Create a new contact",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "required": ["name", "phoneNumber"],
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Oleksii"
                  },
                  "phoneNumber": {
                    "type": "string",
                    "example": 123113355
                  },
                  "email": {
                    "type": "string",
                    "example": "oleksii@example.com"
                  },
                  "isFavourite": {
                    "type": "boolean",
                    "example": true
                  },
                  "contactType": {
                    "type": "string",
                    "enum": ["work", "home", "personal"],
                    "example": "personal"
                  },
                  "photo": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Contact created successfully",
            "content": {
              "application/json": {
                "example": {
                  "status": 201,
                  "message": "Successfully created a contact!",
                  "data": {
                    "name": "contact",
                    "phoneNumber": "1231231212",
                    "isFavourite": false,
                    "contactType": "personal",
                    "userId": "670834b0fcbdc3d8f1b5b009",
                    "_id": "670bfe7b51f30909a5174d36",
                    "createdAt": "2024-10-13T17:08:11.785Z",
                    "updatedAt": "2024-10-13T17:08:11.785Z",
                    "id": "670bfe7b51f30909a5174d36",
                    "page": 1,
                    "perPage": 10,
                    "totalItems": 0,
                    "totalPages": 0,
                    "hasNextPage": true,
                    "hasPreviousPage": false
                  }
                }
              }
            }
          },
          "400": {
            "description": "Contact create failed",
            "content": {
              "application/json": {
                "example": {
                  "status": 400,
                  "message": "BadRequestError",
                  "data": {
                    "message": "Bad Request",
                    "errors": [
                      {
                        "message": "\"phoneNumber\" with value \"123123123\" fails to match the required pattern: /^[0-9]{10,15}$/",
                        "path": ["phoneNumber"],
                        "type": "string.pattern.base",
                        "context": {
                          "regex": {},
                          "value": "123123123",
                          "label": "phoneNumber",
                          "key": "phoneNumber"
                        }
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Missing header with authorization token",
            "content": {
              "application/json": {
                "example": {
                  "status": 401,
                  "message": "UnauthorizedError",
                  "data": {
                    "message": "Session not found"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/contacts/{id}": {
      "get": {
        "tags": ["Contacts"],
        "operationId": "getContactById",
        "summary": "Get contact by ID",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Contact retrieved successfully",
            "content": {
              "application/json": {
                "example": {
                  "status": 200,
                  "message": "Successfully found contact with id 670bfe7b51f30909a5174d36!",
                  "data": {
                    "_id": "670bfe7b51f30909a5174d36",
                    "name": "contact",
                    "phoneNumber": "1231231212",
                    "isFavourite": false,
                    "contactType": "personal",
                    "userId": "670834b0fcbdc3d8f1b5b009",
                    "createdAt": "2024-10-13T17:08:11.785Z",
                    "updatedAt": "2024-10-13T17:08:11.785Z",
                    "id": "670bfe7b51f30909a5174d36"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Missing header with authorization token.",
            "content": {
              "application/json": {
                "example": {
                  "status": 401,
                  "message": "UnauthorizedError",
                  "data": {
                    "message": "Session not found"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Contact not found",
            "content": {
              "application/json": {
                "example": {
                  "status": 404,
                  "message": "NotFoundError",
                  "data": {
                    "message": "Contact not found"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server Error"
          }
        }
      },
      "patch": {
        "tags": ["Contacts"],
        "operationId": "updateContact",
        "summary": "Update contact",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "phoneNumber": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "isFavourite": {
                    "type": "boolean"
                  },
                  "contactType": {
                    "type": "string",
                    "enum": ["work", "home", "personal"]
                  },
                  "photo": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Contact updated successfully",
            "content": {
              "application/json": {
                "example": {
                  "status": 200,
                  "message": "Successfully patched a contact!",
                  "data": {
                    "_id": "670bfe7b51f30909a5174d36",
                    "name": "Andruha",
                    "phoneNumber": "1231231332",
                    "isFavourite": false,
                    "contactType": "personal",
                    "userId": "670834b0fcbdc3d8f1b5b009",
                    "createdAt": "2024-10-13T17:08:11.785Z",
                    "updatedAt": "2024-10-13T17:14:25.949Z",
                    "id": "670bfe7b51f30909a5174d36"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Contact update failed",
            "content": {
              "application/json": {
                "example": {
                  "status": 400,
                  "message": "BadRequestError",
                  "data": {
                    "message": "Bad Request"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Missing header with authorization token.",
            "content": {
              "application/json": {
                "example": {
                  "status": 401,
                  "message": "UnauthorizedError",
                  "data": {
                    "message": "Session not found"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Contact not found",
            "content": {
              "application/json": {
                "example": {
                  "status": 404,
                  "message": "NotFoundError",
                  "data": {
                    "message": "Contact not found or user not authorized"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server Error"
          }
        }
      },
      "delete": {
        "tags": ["Contacts"],
        "operationId": "deleteContact",
        "summary": "Delete contact by ID",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Contact deleted successfully"
          },
          "400": {
            "description": "Contact update failed",
            "content": {
              "application/json": {
                "example": {
                  "status": 400,
                  "message": "BadRequestError",
                  "data": {
                    "message": "Bad Request"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Missing header with authorization token.",
            "content": {
              "application/json": {
                "example": {
                  "status": 401,
                  "message": "UnauthorizedError",
                  "data": {
                    "message": "Session not found"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Contact not found",
            "content": {
              "application/json": {
                "example": {
                  "status": 404,
                  "message": "NotFoundError",
                  "data": {
                    "message": "Contact not found or user not authorized"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server Error"
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    },
    "schemas": {
      "UserRegistration": {
        "type": "object",
        "required": ["name", "email", "password"],
        "properties": {
          "name": {
            "type": "string",
            "example": "Oleksii"
          },
          "email": {
            "type": "string",
            "example": "oleksii@example.com"
          },
          "password": {
            "type": "string",
            "example": "passwordpassword"
          }
        }
      },
      "UserLogin": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "example": "oleksii@example.com"
          },
          "password": {
            "type": "string",
            "example": "passwordpassword"
          }
        }
      },
      "ContactsList": {
        "type": "object",
        "properties": {
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Contact"
            }
          }
        }
      },
      "Contact": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "Oleksii"
          },
          "phoneNumber": {
            "type": "number",
            "example": 123113355
          },
          "email": {
            "type": "string",
            "example": "oleksii@example.com"
          },
          "isFavourite": {
            "type": "boolean",
            "example": true
          },
          "contactType": {
            "type": "string",
            "example": "personal"
          },
          "photo": {
            "type": "string",
            "example": "http://example.com/photo.jpg"
          }
        }
      }
    }
  }
}
